### ISSUE TITLE
Setup Lakpa VM build

### ISSUE THREAD

**Issue by tylerfranklin** [CUNY-Computer-Vision-Lab/collab-xr#15]
Estimate: 5
Value: 5

**Comment by tylerfranklin** [comment]
Re: USB passthrough https://forums.virtualbox.org/viewtopic.php?f=35&t=82639

**Comment by tylerfranklin** [comment]
https://download.virtualbox.org/virtualbox/6.0.10/Oracle_VM_VirtualBox_Extension_Pack-6.0.10.vbox-extpack

**Comment by LakpaSherpa123** [comment]
HI

**Comment by tylerfranklin** [comment]
Tabling this until we can find another workaround.
